services:
  backend:
    image: dnwn7166/board-backend:latest
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    image: dnwn7166/board-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
