apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-backend
  namespace: board-service
  labels:
    app: board-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: board-backend
  template:
    metadata:
      labels:
        app: board-backend
    spec:
      containers:
      - name: board-backend
        image: dnwn7166/board-backend:latest
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 0  # Run as root to have permission to create directories
        volumeMounts:
        - name: app-logs
          mountPath: /var/log/app
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: board-service-config
              key: NODE_ENV
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: board-service-secrets
              key: MONGODB_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: board-service-secrets
              key: JWT_SECRET
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      
      volumes:
      - name: app-logs
        hostPath:
          path: /var/log/app
          type: DirectoryOrCreate
