apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-frontend
  namespace: board-service
  labels:
    app: board-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: board-frontend
  template:
    metadata:
      labels:
        app: board-frontend
    spec:
      containers:
      - name: board-frontend
        image: dnwn7166/board-frontend:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/app/board-service/nginx
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      
      - name: vector-sidecar
        image: timberio/vector:0.35.0-alpine
        ports:
        - containerPort: 8686
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONTAINER_NAME
          value: "vector-sidecar"
        volumeMounts:
        - name: nginx-logs
          mountPath: /var/log/app/board-service/nginx
        - name: vector-config
          mountPath: /etc/vector
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8686
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8686
          initialDelaySeconds: 5
          periodSeconds: 5
      
      volumes:
      - name: nginx-logs
        persistentVolumeClaim:
          claimName: nginx-logs-pvc
      - name: vector-config
        configMap:
          name: vector-sidecar-config